name: pandorora_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #navigation
  auto_route: ^3.2.4
  
  #network
  dio: ^4.0.4

  #service locator
  get_it: ^7.2.0

  #localDb
  hive_flutter: ^1.1.0

  #tools
  dart_jsonwebtoken: ^2.4.1
  equatable: ^2.0.3
  flutter_dotenv: ^5.0.2
  bloc_concurrency: ^0.2.0
  stream_transform: ^2.0.0
  connectivity_plus: ^2.2.1
  #state management
  flutter_bloc: ^8.0.1

  #UI
  
  #MY_MODULES---------------------
  
  #firebase_auth_rest
  firebase_auth_rest:
    path: modules/firebase_auth_rest

  country_phone_picker:
    path: modules/country_phone_picker

  cupertino_icons: ^1.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  #code generators
  build_runner: ^2.1.7
  auto_route_generator: ^3.2.1
  #linter
  flutter_lints: ^1.0.0


flutter:

  fonts:
    - family: red-hat
      fonts:
        - asset: assets/fonts/red-hat-font.ttf 
    - family: TechnaSans
      fonts:
        - asset: assets/fonts/TechnaSans-Regular.otf    
  assets:
 
    - .env

  uses-material-design: true
